imports:
    - { resource: tables.yml }

services:
    sheer.ptrequest.controller:
        class: sheer\ptrequest\controller\ptrequest
        arguments:
            - @dbal.conn
            - @template
            - @user
            - @cache
            - %tables.ptrequest%
    sheer.ptrequest.listener:
        class: sheer\ptrequest\event\listener
        arguments:
            - @template
            - @controller.helper
            - %core.root_path%
        tags:
            - { name: event.listener }
